#!/bin/sh

# the file where the commit message is written
filepath="$1"
tmp_file=$(mktemp /tmp/emoji-commitzen.XXXX)

replacements=(
    's/^new/✨ Feat:/'
    's/^New/✨ Feat:/'
    's/^add/✨ Feat: add/'
    's/^Add/✨ Feat: add/'
    's/^feat/✨ Feat:/'
    's/^Feat/✨ Feat:/'
    's/^fonc/✨ Feat:/'
    's/^Fonc/✨ Feat:/'
    's/^fix/🐛 Fix:/'
    's/^Fix/🐛 Fix:/'
    's/^doc/📚 Doc:/'
    's/^Doc/📚 Doc:/'
    's/^style/🎨 Style:/'
    's/^Style/🎨 Style:/'
    's/^compile/🎨 Style:/'
    's/^Compile/🎨 Style:/'
    's/^recompile/🎨 Style:/'
    's/^Recompile/🎨 Style:/'
    's/^format/🔨 Refact:/'
    's/^Format/🔨 Refact:/'
    's/^refacto/🔨 Refact:/'
    's/^Refacto/🔨 Refact:/'
    's/^update/🔨 Refact:/'
    's/^Update/🔨 Refact:/'
    's/^move/🔨 Refact:/'
    's/^Move/🔨 Refact:/'
    's/^perf/🚀 Perf:/'
    's/^Perf/🚀 Perf:/'
    's/^chore/🔧 Chore:/'
    's/^Chore/🔧 Chore:/'
    's/^config/🤖 CI:/'
    's/^Config/🤖 CI:/'
    's/^lint/💄 Lint:/'
    's/^Lint/💄 Lint:/'
    's/^test/🧪 Test:/'
    's/^Test/🧪 Test:/'
    's/^release/📦 Release:/'
    's/^Release/📦 Release:/'
    's/^first/🐣 First:/'
    's/^First/🐣 First:/'
    's/^remove/❌ Del:/'
    's/^Remove/❌ Del:/'
    's/^delete/❌ Del:/'
    's/^Delete/❌ Del:/'
    's/^revert/🔁 Revert:/'
    's/^Revert/🔁 Revert:/'
)

# join replacements by ; to have sed perform multiple replace
sed_command=$(printf "%s;" "${replacements[@]}")

# perform replacements in temp file
result=$(cat $filepath | sed "$sed_command")

# if there are brackets in the commit message, remove the colon
brackets_regex="\(([^()]*)\)"
for s in ${result[@]}; do
    if [[ ${s} =~ $brackets_regex ]]; then
        result=$(echo "$result" | sed "s/:(/(/")
    fi
done

# write result to temp file
echo $result > $tmp_file

# replace commit file
mv $tmp_file $filepath
