#!/bin/sh

# the file where the commit message is written
filepath="$1"
tmp_file=$(mktemp /tmp/emoji-commitzen.XXXX)

replacements=(
    's/^new/✨ Feat:/'
    's/^New/✨ Feat:/'
    's/^add/✨ Feat: add/'
    's/^Add/✨ Feat: add/'
    's/^feat/✨ Feat:/'
    's/^Feat/✨ Feat:/'
    's/^fix/🐛 Fix:/'
    's/^Fix/🐛 Fix:/'
    's/^doc/📚 Doc:/'
    's/^Doc/📚 Doc:/'
    's/^style/🎨 Style:/'
    's/^Style/🎨 Style:/'
    's/^compile/🎨 Style:/'
    's/^Compile/🎨 Style:/'
    's/^recompile/🎨 Style:/'
    's/^Recompile/🎨 Style:/'
    's/^format/🔨 Refact:/'
    's/^Format/🔨 Refact:/'
    's/^refacto/🔨 Refact:/'
    's/^Refacto/🔨 Refact:/'
    's/^update/🔨 Refact:/'
    's/^Update/🔨 Refact:/'
    's/^perf/🚀 Perf:/'
    's/^Perf/🚀 Perf:/'
    's/^chore/🔧 Chore:/'
    's/^Chore/🔧 Chore:/'
    's/^config/🔧 Conf:/'
    's/^Config/🔧 Conf:/'
    's/^lint/💄 Lint:/'
    's/^Lint/💄 Lint:/'
    's/^test/🤖 Test:/'
    's/^Test/🤖 Test:/'
    's/^release/📦 Release:/'
    's/^Release/📦 Release:/'
    's/^first/🐣 First:/'
    's/^First/🐣 First:/'
    's/^remove/❌ Del:/'
    's/^Remove/❌ Del:/'
    's/^delete/❌ Del:/'
    's/^Delete/❌ Del:/'
    's/^move/🔁 Move:/'
    's/^Move/🔁 Move:/'
)

# join replacements by ; to have sed perform multiple replace
sed_command=$(printf "%s;" "${replacements[@]}")

# perform replacements in temp file
cat $filepath | sed "$sed_command" > $tmp_file

# replace commit file
mv $tmp_file $filepath
