name: ✍ git-cliff - Changelog Generator

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for specific branches
  push:
    branches: [ main ]
    # paths-ignore:
    #   - 'docs/**'
    #   - '.github/**'
    #   - 'README.m**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-changelog:
    # You may pin to the exact commit or the version.
    # uses: orhun/git-cliff-action@8b17108aad4d9362649a5dae020746c2a767c90d
    uses: orhun/git-cliff-action@v3.0.2
    # with:
    #   config file location
    #   config: # optional, default is cliff.toml
    #   git-cliff arguments
    #   args: # optional, default is -v
