name: ✍ Generate Changelog / Release notes (git-cliff)

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for specific branches
  push:
    branches: [ main ]
    # paths-ignore:
    #   - 'docs/**'
    #   - '.github/**'
    #   - 'README.m**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    run-changelog-generator:
      name: Run Changelog Generator (git-cliff)
      runs-on: ubuntu-latest
      outputs:
        release_body: ${{ steps.git-cliff.outputs.content }}
      steps:
        - name: Check out repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
      
        - name: Generate changelog
          uses: orhun/git-cliff-action@v3
          id: git-cliff
          with:
            # config file location
            config: cliff.toml
            # git-cliff arguments - https://git-cliff.org/docs/usage/args
            args: --bump -v # optional, default is -v
